global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbit:15692']

  - job_name: 'cybertech-administration-api'
      metrics_path: /metrics
      static_configs:
        - targets: ['cybertech-administration-api:8080']